NEW Convert to vendor module
silverstripe/comment-notifications pull request #26
Opened 2017-12-12 03:53 UTC by robbieaverill

2017-12-12 11:14 UTC, dhensby requested changes

2017-12-12 11:14 UTC, dhensby commented on tests/CommentNotifiableTest.php
> +        $this->assertEquals(['myadmin@mysite.com', 'andrew@address.com'), $item1->notificationRecipients($comment1)]);
You've not closed the array properly here

```diff
-$this->assertEquals(['myadmin@mysite.com', 'andrew@address.com'), $item1->notificationRecipients($comment1)]);`
+$this->assertEquals(['myadmin@mysite.com', 'andrew@address.com'], $item1->notificationRecipients($comment1));
-$this->assertEquals(['myadmin@mysite.com'), $item2->notificationRecipients($comment2)]);
+$this->assertEquals(['myadmin@mysite.com'], $item2->notificationRecipients($comment2));
```

2017-12-12 20:37 UTC, robbieaverill commented
PHP 7.2 builds fixed here: https://github.com/colymba/GridFieldBulkEditingTools/pull/156

2017-12-13 09:42 UTC, robbieaverill commented
Builds fixed

2017-12-13 12:06 UTC, merged